### ISSUE TITLE
Can't finalize hatching - hybrid egg

### ISSUE THREAD

**Issue by Sc0rp1c** [Kitsumon/breeding-testnet#12]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ y] Have you cleared your cache?
- [y ] Enter Browser name and version: Kiwi browser 101.0.4951.40
- [y ] Enter Wallet name and version: Metamask Version 10.14.6
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### Steps to Reproduce

1. https://breeding.vercel.app/dex/0x8bab2760501151b4dbfdad8f1d5167936b35087f/62
2.
3.
4.

**Comment by JayArrowz** [comment]
Presume this was fixed as we made a update subsequent to this
