### ISSUE TITLE
Clipped tail of a JSP hybrid

### ISSUE THREAD

**Issue by balamon** [Kitsumon/breeding-testnet#13]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ ] Have you cleared your cache? yes 
- [ ] Enter Browser name and version: Chrome version 101.0.4951.67
- [ ] Enter Wallet name and version: 0x940e904951fe56df9fb8ae2f2a124A0357bFcdC5 MetaMask Version 10.14.6
- [ ] Enter transaction ID if any: N/A

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

The tail is clipped in the model and appears out of place.

### Expected Behavior

The tail should attach nicely to the end of the kitsu.

### Current Behavior

The tail is clipped in the model and appears out of place.
### Steps to Reproduce

https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/205

![Capture](https://user-images.githubusercontent.com/71768001/170176891-56d45f51-9ef7-461a-a685-8a36c2413458.JPG)

1.
2.
3.
4.

### Context (Environment)

 N/A
 N/A
 Tune the JSP kitsu model

### Detailed Description

 Tune the JSP kitsu model

**Comment by JayArrowz** [comment]
Fixed
![image](https://user-images.githubusercontent.com/49910176/171319370-a3041303-a0f5-48a9-a583-744227f2427e.png)
