### ISSUE TITLE
Aquajet spinning fans

### ISSUE THREAD

**Issue by balamon** [Kitsumon/breeding-testnet#14]
## Feature Request

**Is your feature request related to a problem? Please describe.** Yes, aquajet pack fans spinning for hybrid with JSP DNAbut not for actual aquajet kitsu.

Spinning fan:
https://user-images.githubusercontent.com/71768001/170177377-4f9ed83b-e4aa-4c6d-aa73-6a7e7e3c22f9.mov

No spinning fan:
https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/182

No spinning fan another model:
https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/195

**Describe the solution you'd like**
For aquajet pack fan to be spinning for Aquajet kitsu and on all hybrids

**Describe alternatives you've considered**
N/A

**Teachability, Documentation, Adoption, Migration Strategy**
See above video of the fan spinning

**Comment by JayArrowz** [comment]
Not too sure where this belongs in but not a show stopper.
Seems maybe animation frames are not being copied sometimes?

**Comment by JayArrowz** [comment]
Not bug
