### ISSUE TITLE
Cloverfield legs

### ISSUE THREAD

**Issue by Mistbind** [Kitsumon/breeding-testnet#16]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ ] Have you cleared your cache? Yes
- [ ] Enter Browser name and version: metamask
- [ ] Enter Wallet name and version: metamask version 5.1.1
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### Steps to Reproduce

1. Bred 777 and Cloverfield 
2. Issue probably visible on others that get Cloverfield legs and color
3.
4.

### Detailed Description

Adjust the legs color, possibly change the top yellow part, and adjust inner length or alignment to hide stitching 
![Screenshot_20220525-053835_MetaMask](https://user-images.githubusercontent.com/105953165/170246474-e88a927c-e75c-4d30-a9dc-31332225ba41.jpg)
![Uploading Screenshot_20220525-054257_MetaMask.jpg…]()

**Comment by JayArrowz** [comment]
Fixed: 
![image](https://user-images.githubusercontent.com/49910176/171751278-7d6d448a-0721-4a7d-8000-73bb4c5de80c.png)
