### ISSUE TITLE
Hybrid Tail Issue

### ISSUE THREAD

**Issue by ghost** [Kitsumon/breeding-testnet#18]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ ] Have you cleared your cache?
- [ ] Enter Browser name and version: .e.g. Chrome 11
- [ ] Enter Wallet name and version: XXX Version x.xx (.e.g Metamask Version 1.2.0)
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

## Bug reports: Tail gap for hybrid of Pharaoha and Negativo
![WhatsApp Image 2022-05-25 at 20 29 26](https://user-images.githubusercontent.com/106227816/170328582-5cb6d673-46a3-4d17-b54f-2aab35c12df8.jpeg)

[https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/247](url)

![WhatsApp Image 2022-05-25 at 20 29 44](https://user-images.githubusercontent.com/106227816/170328873-354d3510-1823-41db-b4d5-a09133cb6d80.jpeg)

[https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/228](url)

![WhatsApp Image 2022-05-25 at 20 30 02](https://user-images.githubusercontent.com/106227816/170329088-cb0b94b5-b062-4bb7-b07d-94a742a4ea97.jpeg)

[https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/89](url)
### Steps to Reproduce

1.
2.
3.
4.

**Comment by JayArrowz** [comment]
Fixed when new models are out:
![image](https://user-images.githubusercontent.com/49910176/171319690-405d7cac-71d1-42db-ba92-24ce52348814.png)
![image](https://user-images.githubusercontent.com/49910176/171319893-fe5a56b0-68a4-4818-9fe4-50d7aff324b0.png)
