### ISSUE TITLE
Necklace/Neck part issue

### ISSUE THREAD

**Issue by ghost** [Kitsumon/breeding-testnet#19]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ ] Have you cleared your cache?
- [ ] Enter Browser name and version: .e.g. Chrome 11
- [ ] Enter Wallet name and version: XXX Version x.xx (.e.g Metamask Version 1.2.0)
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

## Bug reports: Pharaoha's necklace and Negativo's neck part are both taking place at the same time.

[https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/250](url)

![WhatsApp Image 2022-05-25 at 20 30 34](https://user-images.githubusercontent.com/106227816/170329500-aeaa76be-ef0d-4037-b706-6420346d2591.jpeg)

### Steps to Reproduce

1.
2.
3.
4.

**Comment by JayArrowz** [comment]
This is because the chest of negativo is attached to the body as a single mesh.
Instead we need a seperate chest mesh for negativo so we can trade out the chest pieces accordingly

**Comment by JayArrowz** [comment]
Fixed with new models
