### ISSUE TITLE
Cannot enter Test-net Marketplace

### ISSUE THREAD

**Issue by Xkyee30** [Kitsumon/breeding-testnet#2]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [Yes] Have you cleared your cache?
- [Metamask Browser] Enter Browser name and version: .e.g. Chrome 11
- [0x055FE31Ea38751311ce8e066dd43fF9e91b214A7 Metamask v5.1.1(906)] Enter Wallet name and version: XXX Version x.xx (.e.g Metamask Version 1.2.0)
- [XXX] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

Try to access the http://marketplace-test.kitsumon.com/ and the error showed.
Rechecked the settings, clear cache and refresh many times. Nothing happened.

## Bug reports:
![Screenshot_20220524-231539](https://user-images.githubusercontent.com/106165471/170086867-09960c6f-4c16-4f64-bd5c-75c20515edea.jpg)

### Expected Behavior

Can't load and redirecting to the same error page.

### Current Behavior

On the second try it doesn't load the page.

### Steps to Reproduce

1.
2.
3.
4.

### Context (Environment)

Testing it on mobile.

Android 11

**Comment by JayArrowz** [comment]
https://marketplace-test.kitsumon.com/
