### ISSUE TITLE
Breeding Failed

### ISSUE THREAD

**Issue by Ky0ushu** [Kitsumon/breeding-testnet#21]
I tried to breed a Phoenixa and a Geodite

I approved the transaction

The Breeding process failed but the potion was used - Error Message "BREEDING FAILED"

Both Kitsus are on cooldown now

After some time a hybrid egg popped up and I was able to hatch it

<img width="705" alt="Screenshot 2022-05-26 at 00 31 34" src="https://user-images.githubusercontent.com/106195618/170380805-2c81e733-a7c1-4de0-b8cf-ecc8dae02343.png">

## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ ] Have you cleared your cache?
- [ ] Enter Browser name and version: .e.g. Chrome 11
- [ ] Enter Wallet name and version: XXX Version x.xx (.e.g Metamask Version 1.2.0)
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### Steps to Reproduce

1.
2.
3.
4.

**Comment by JayArrowz** [comment]
Newer version of breeding will be coming out shortly which will allow the user to do only 2 transactions.
