### ISSUE TITLE
Golderado helmet

### ISSUE THREAD

**Issue by Mistbind** [Kitsumon/breeding-testnet#23]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ x] Have you cleared your cache?
- [ ] Enter Browser name and version: metamask
- [ ] Enter Wallet name and version: metamask 5.1.1
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### Expected Behavior

It should be a solid object that moves with the head 

### Current Behavior

On every variant the ears pop in and out of the helmet 

### Possible Solution

Make golderado helmet a head element without the underlying edition of ears or make it so big it doesn't  matter like 777s hat

### Steps to Reproduce

1. Look at any golderado animation and zoom in on helmet/ears 
3.
4.
5.

### Detailed Description

Example model: https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/852
![image](https://user-images.githubusercontent.com/49910176/171741834-4bea5f7e-1ee6-4bb2-9828-fbfe640ee876.png)

Remove or put in fix position the ears under the helmet so they stop poking through 
![Screenshot_20220525-203421_MetaMask](https://user-images.githubusercontent.com/105953165/170398883-21bd231e-2b2a-4e64-82d6-160b4c3a4d6b.jpg)
![Screenshot_20220525-203419_MetaMask](https://user-images.githubusercontent.com/105953165/170398895-7a11e322-1954-4577-a41d-9b6ae271a82f.jpg)
![Screenshot_20220525-203417_MetaMask](https://user-images.githubusercontent.com/105953165/170398899-4c92afeb-d908-4733-84c3-22ba09852600.jpg)

**Comment by JayArrowz** [comment]
Fixed
