### ISSUE TITLE
Vampsu gen tail issue

### ISSUE THREAD

**Issue by ghost** [Kitsumon/breeding-testnet#24]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ ] Have you cleared your cache?
- [ ] Enter Browser name and version: .e.g. Chrome 11
- [ ] Enter Wallet name and version: XXX Version x.xx (.e.g Metamask Version 1.2.0)
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

## Bug reports:There is no fluffy part of Vampsu tail on this hybrid
 [https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/409](url)

![CCJ Tail Issue](https://user-images.githubusercontent.com/106227816/170437861-b1c8049e-8e6d-4b99-acfa-fc51fd77fc3e.png)

### Steps to Reproduce

1.
2.
3.
4.

**Comment by JayArrowz** [comment]
Not bug, the fluffy tail is not apart of this bodypart :P
