### ISSUE TITLE
Finalize Hatch issue for hybrid egg

### ISSUE THREAD

**Issue by ghost** [Kitsumon/breeding-testnet#25]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ ] Have you cleared your cache?
- [ ] Enter Browser name and version: .e.g. Chrome 11
- [ ] Enter Wallet name and version: XXX Version x.xx (.e.g Metamask Version 1.2.0)
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

## Bug reports: Not able to finalize hatching for more than 12 hours. Egg got stucked on pending tab.
[https://breeding.vercel.app/dex/0x8bab2760501151b4dbfdad8f1d5167936b35087f/126](url)

### Steps to Reproduce

1.
2.
3.
4.

**Comment by JayArrowz** [comment]
Please retry, we have made this process more stable.

**Comment by JayArrowz** [comment]
f69ee172-25de-487c-8298-ff8145798eaf

**Comment by JayArrowz** [comment]
This has been fixed, had a issue with render pipeline, but no more
![output](https://user-images.githubusercontent.com/49910176/171759469-2956ab8d-a5fd-428d-a662-cc30045b2fef.png)
.
