### ISSUE TITLE
Both chest at once and lines on back legs stitching

### ISSUE THREAD

**Issue by Sc0rp1c** [Kitsumon/breeding-testnet#27]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ y] Have you cleared your cache?
- [ y] Enter Browser name and version: Mozilla 100.0.2
- [y ] Enter Wallet name and version: Metamask Version 10.12.4
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### Steps to Reproduce

1. https://marketplace-test.kitsumon.com/accounts/0x9e08da9b334d8444716253a49c39ae7d31622ee2/sell-item/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/414
2. https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/414
3. 
![Screenshot_2022-05-26-09-36-30-936](https://user-images.githubusercontent.com/105955114/170453551-b085073a-af86-433c-8238-bd3d4f344c43.jpg)
![Screenshot_2022-05-26-09-36-22-198](https://user-images.githubusercontent.com/105955114/170453558-e5a0df57-1b36-414e-a291-fe14fdffcb32.jpg)

4.

**Comment by JayArrowz** [comment]
Remains

**Comment by JayArrowz** [comment]
Fixed - wont fix the chest
