### ISSUE TITLE
Tail clipping

### ISSUE THREAD

**Issue by Sc0rp1c** [Kitsumon/breeding-testnet#29]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ y] Have you cleared your cache?
- [ y] Enter Browser name and version: mozilla 100.0.2
- [ y] Enter Wallet name and version:  Metamask Version 10.12.4
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### Steps to Reproduce

1. 
![2022-05-26 (13)](https://user-images.githubusercontent.com/105955114/170463118-a2ad1804-7396-4119-8e09-ca9cdc40c4c5.png)

2. https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/447
3. https://marketplace-test.kitsumon.com/accounts/0x9e08da9b334d8444716253a49c39ae7d31622ee2/sell-item/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/447
4.

**Comment by JayArrowz** [comment]
Fixed
