### ISSUE TITLE
Gaps between Body and limbs

### ISSUE THREAD

**Issue by Ky0ushu** [Kitsumon/breeding-testnet#30]
I bred my Geodite/Phoenixa Hybrid with a pure Baalimon

There are visible gaps between body and limbs

Here are 2 pictures of it:
<img width="526" alt="Screenshot 2022-05-26 at 12 02 22" src="https://user-images.githubusercontent.com/106195618/170466239-adf642d4-055e-4b25-9c42-0a62495f6aa7.png">
<img width="451" alt="Screenshot 2022-05-26 at 11 59 24" src="https://user-images.githubusercontent.com/106195618/170466259-e01d8c38-54f4-4cdb-beeb-3ddf845ea597.png">

The Geodite/Phoenixa Hybrid also has a slight gap on the front legs - you can see it here:
<img width="202" alt="Screenshot 2022-05-26 at 12 05 23" src="https://user-images.githubusercontent.com/106195618/170466780-e243975c-cdaa-4c41-83d2-9946e622cb33.png">

**Comment by JayArrowz** [comment]
Fixed
