### ISSUE TITLE
Elemental affinity change

### ISSUE THREAD

**Issue by Xkyee30** [Kitsumon/breeding-testnet#31]
WISE GOOD MELON
ID #292

Breeding with Geodite Inherit the LIGHT element.
Or is it possible to be active with Skyfall element? AIR/ LIGHTNING that can be passed down to its offspring and also second parent elemental active affinity like Geodite Earth/Light.

Because I always got a first parent active elements. Never seen this kind of AIR/LIGHT.

Maybe I was wrong with the hybrid elements.

![Screenshot_20220525-231245](https://user-images.githubusercontent.com/106165471/170473568-1110b5c4-3fb9-4ccb-93f0-089a12f41616.jpg)

**Comment by JayArrowz** [comment]
Affinity changes are described in this topic here: https://github.com/Kitsumon/breeding-testnet/issues/49
