### ISSUE TITLE
Giggawat tail misplaced

### ISSUE THREAD

**Issue by Ky0ushu** [Kitsumon/breeding-testnet#32]
This hybrid model has its right tail slightly misplaced:

https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/491

<img width="702" alt="Screenshot 2022-05-26 at 14 37 10" src="https://user-images.githubusercontent.com/106195618/170496685-daf862f5-c726-4a61-b4df-0f17d4b62a2d.png">
<img width="488" alt="Screenshot 2022-05-26 at 14 38 16" src="https://user-images.githubusercontent.com/106195618/170496669-4595aca2-f18d-4a31-a297-8a4572a214f3.png">

**Comment by JayArrowz** [comment]
Issue is fixed with new models 

![image](https://user-images.githubusercontent.com/49910176/171316764-0e05a95c-782b-46cc-b80f-a57b084c12d4.png)
