### ISSUE TITLE
Leg part Gaps

### ISSUE THREAD

**Issue by Xkyee30** [Kitsumon/breeding-testnet#33]
Tiny small gaps of skyfall legs.

WISE GOOD MELON
ID #292

![Screenshot_20220526-233114](https://user-images.githubusercontent.com/106165471/170522171-f83339d2-135d-4f83-9591-8ad264f2e913.jpg)
![Screenshot_20220526-233206](https://user-images.githubusercontent.com/106165471/170522193-9faefc82-3cf4-496e-8651-17c185f922d0.jpg)

**Comment by JayArrowz** [comment]
Should be fixed via weight painting

**Comment by JayArrowz** [comment]
Fixed with new models:
![image](https://user-images.githubusercontent.com/49910176/171318624-853e5429-1794-486d-a10e-e4b975d7a616.png)
