### ISSUE TITLE
Hybrid and Potion cancellation failed

### ISSUE THREAD

**Issue by Xkyee30** [Kitsumon/breeding-testnet#36]
## Bug reports:

I can use my hybrid redemption card and potion in breeding app while it is listed on the marketplace.

### Expected Behavior
Cannot delist the item because I used the redemption card and hatch it and used the potion to breed into another hybrid.

### Current Behavior

Cannot delist the item in the marketplace.

### Possible Solution

The items that is being sell or listed in marketplace must not be used for breeding.

### Steps to Reproduce

1. First, I listed the items(potion and hybrid card)
![Screenshot_20220526-235241](https://user-images.githubusercontent.com/106165471/170537368-e4e90e89-7b6c-4349-8e05-1c5d2eff22f3.jpg)

2. Checking the item if it is in the My nfts.
This I item should not be here because it is listed.
![Screenshot_20220527-000906](https://user-images.githubusercontent.com/106165471/170535738-505684f0-482b-4ecc-9838-73fd82583182.jpg)
3. I hatched this hybrid and this is the result.
![Screenshot_20220527-002109](https://user-images.githubusercontent.com/106165471/170536137-a2e4415a-0987-48a7-b996-6ef6a89f7707.jpg)
4. I used the potion in the breeding process.
5. Now, both items cannot be cancelled in the marketplace. #38 and #39 

![Screenshot_20220527-003432](https://user-images.githubusercontent.com/106165471/170536336-1ebc29cb-c581-4cd3-b0ae-a16ef9a93618.jpg)

### Context (Environment)

Trying to sell while breeding in the app.

Metamask Mobile Browser.

The listed item should not be available in the breeding app. This may cause more items to have a bug.

### Detailed Description

The potion should not be also used for breeding if is listed in the marketplace.

**Comment by JayArrowz** [comment]
This will be fixed on contract upgrade.
