### ISSUE TITLE
Arrangement and color of body parts

### ISSUE THREAD

**Issue by Ky0ushu** [Kitsumon/breeding-testnet#37]
This Hybrid has a slightly misplaced tail:
https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/535

Also the color of the back legs does not match the body color
<img width="663" alt="Screenshot 2022-05-26 at 19 15 15" src="https://user-images.githubusercontent.com/106195618/170540504-737ffd42-7490-408c-b92e-849d4984c46a.png">

**Comment by JayArrowz** [comment]
Has a JSP chest inside it, can be the root of all our issues here.

**Comment by JayArrowz** [comment]
Fixed on update
![image](https://user-images.githubusercontent.com/49910176/171320199-0bd0c81e-62e1-411c-a224-786ad20243a3.png)
