### ISSUE TITLE
Potion #334 Used Potions

### ISSUE THREAD

**Issue by Xkyee30** [Kitsumon/breeding-testnet#38]
## Bug reports:

Continuation of bug #36 
Bug items cannot be bought in the marketplace

### Expected Behavior

Buying potion ID#334 transaction failed.

### Current Behavior

Approved the contract but the item cannot be purchased.

### Steps to Reproduce

1. Potion in the marketplace.
![Screenshot_20220527-013616](https://user-images.githubusercontent.com/106165471/170544895-3c087df5-d804-4d61-8293-219d59ac44f1.jpg)
2. Purchasing the bug potion cause the item failed.
![Screenshot_20220527-014222](https://user-images.githubusercontent.com/106165471/170545038-f716d8a3-431a-489b-8290-bfb9a0777fac.jpg)

3.
4.

### Context (Environment)

Cost gas to approved the item.

Metamask Mobile

Avoiding the bug potions

**Comment by JayArrowz** [comment]
Old potions fixed
