### ISSUE TITLE
Hybrid ID#220 unhatched eggs

### ISSUE THREAD

**Issue by Xkyee30** [Kitsumon/breeding-testnet#39]
## Bug reports:
Continuation of bug #36

### Expected Behavior
Appear bug redemption cards in the marketplace

### Current Behavior

Hybrid ID#220 cannot be bought.

### Steps to Reproduce

1. Bug hybrids listed on the marketplace
![Screenshot_20220527-015402](https://user-images.githubusercontent.com/106165471/170547549-a0512154-0f61-45ab-b294-753498158669.jpg)

2. Buying the item transaction failed.
![Screenshot_20220527-015423](https://user-images.githubusercontent.com/106165471/170547633-b03c5578-62a5-4140-bf40-8d07a9d18c93.jpg)

### Context (Environment)

This item may be more issue in the marketplace.
Avoiding the possible cause.

**Comment by JayArrowz** [comment]
Will be fixed on upgrade of contracts
