### ISSUE TITLE
Kitsudex #1 Negativo

### ISSUE THREAD

**Issue by Xkyee30** [Kitsumon/breeding-testnet#40]
Miniature model pixilated.

Metamask Mobile

![Screenshot_20220527-101550](https://user-images.githubusercontent.com/106165471/170617356-1a4910ab-8ab1-4cc2-84a6-5a527a78a341.jpg)

**Comment by JayArrowz** [comment]
This is cause i rendered it with a GPU. Caused some weird results. Need to replace generated model image

**Comment by JayArrowz** [comment]
Fixed
