### ISSUE TITLE
Hybrid eye coming from Cracked gen

### ISSUE THREAD

**Issue by ghost** [Kitsumon/breeding-testnet#42]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ ] Have you cleared your cache?
- [ ] Enter Browser name and version: .e.g. Chrome 11
- [ ] Enter Wallet name and version: XXX Version x.xx (.e.g Metamask Version 1.2.0)
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

## Bug reports: I'm not sure to call it as a bug, because the Cracked eye is under bandage. But it looks weird without bandage. The eye under bandage could be as the other eye (normal) under bandage. So hybrid kitsus could take both eyes as normal right eye of Cracked.

[https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/488](url)

![Cracked Hybrid eye thing](https://user-images.githubusercontent.com/106227816/170775289-e4f4df91-2090-4824-ab25-3c306b441d45.jpg)

### Steps to Reproduce

1.
2.
3.
4.

**Comment by JayArrowz** [comment]
Not a issue, this is because one of the colour palettes was black
