### ISSUE TITLE
Visible gaps - body & limbs

### ISSUE THREAD

**Issue by Ky0ushu** [Kitsumon/breeding-testnet#43]
This Hybrid has visible gaps on both front and back legs:

https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/683
<img width="750" alt="Screenshot 2022-05-27 at 23 42 15" src="https://user-images.githubusercontent.com/106195618/170792829-173332b9-4532-4abf-8692-3b246010cce7.png">

**Comment by JayArrowz** [comment]
- Pharoha fixed on update
- Awaiting Vampsu fixed weight paint

**Comment by JayArrowz** [comment]
Fixed with new models:
![image](https://user-images.githubusercontent.com/49910176/171317717-1287c8fd-bced-439f-a0eb-44aa0ede6d97.png)
