### ISSUE TITLE
Search only searches first element not both

### ISSUE THREAD

**Issue by Mistbind** [Kitsumon/breeding-testnet#44]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [x ] Have you cleared your cache? Yes
- [ ] Enter Browser name and version: metamask
- [ ] Enter Wallet name and version: metamask 5.1.1 
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### Expected Behavior
To show results of both elements or a kitsu

### Current Behavior

Shows only results for first elements not second element example kistune is Fire/Mana when use search on Mana Kitsune does not show, but she will show on fire search

Also no results for potions show up

### Possible Solution
Have search show results for both elements rather then only the first

### Steps to Reproduce

1. Go to search feature click an element 
![Screenshot_20220527-171108_MetaMask](https://user-images.githubusercontent.com/105953165/170796081-4a3705f6-0896-4755-9628-b61f6340cbc5.jpg)
![Screenshot_20220527-171157_MetaMask](https://user-images.githubusercontent.com/105953165/170796082-419cde73-fd63-4e6f-aeff-719ad3df4aec.jpg)
![Screenshot_20220527-171237_MetaMask](https://user-images.githubusercontent.com/105953165/170796085-f893367a-8468-48a0-83ba-b06d984339bd.jpg)
![Screenshot_20220527-171248_MetaMask](https://user-images.githubusercontent.com/105953165/170796087-92a2f2e5-f236-4e94-b061-964e9cefe2b0.jpg)
![Screenshot_20220527-171316_MetaMask](https://user-images.githubusercontent.com/105953165/170796091-24d1d422-694c-4845-9caa-952e07c029ce.jpg)

2.
3.
4.

**Comment by JayArrowz** [comment]
how this was intended to work is your first selection will filter primary type the second selection will filter secondary type.


.e.g. lets say you selected Air then Water
The filter will be searching for Primary Air and Secondary Water. 

If you deselect Air it'll search Primary water

If anyone has ideas on UI improvements to this we can raise a feature ticket

**Comment by JayArrowz** [comment]
Marked potions as a bug...
Low priority as i guess a user can de-select the attribute filters then they'd be able to view the potions?

**Comment by Mistbind** [comment]
I see I had expected both elements to be 'equal' not hierarchy of one and
two, in use trying to breed for affinity I expected anything with Mana as a
base element to show up when i clicked Mana.
Sorry that it's the second report I put in that were evidently intended as
features.

**Comment by JayArrowz** [comment]
Fixed - new search system has been added
