### ISSUE TITLE
Misplaced tail

### ISSUE THREAD

**Issue by Ky0ushu** [Kitsumon/breeding-testnet#45]
This Kitsu has a misplaced tail again - it is a hybrid of 5th generation
https://breeding.vercel.app/dex/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/746
<img width="683" alt="Screenshot 2022-05-29 at 00 03 11" src="https://user-images.githubusercontent.com/106195618/170844304-1c1464a7-5337-4ae4-8438-d06c3585ec52.png">

**Comment by JayArrowz** [comment]
Fixed on update: 
![image](https://user-images.githubusercontent.com/49910176/171320558-0d86de39-a538-47b0-ba24-23177c5b878d.png)
