### ISSUE TITLE
Multiple listing kitsu

### ISSUE THREAD

**Issue by Mistbind** [Kitsumon/breeding-testnet#46]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [x ] Have you cleared your cache? Yes
- [ ] Enter Browser name and version: metamask
- [ ] Enter Wallet name and version: metamask 5.1.1
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### Expected Behavior

To be able to post a kitsu on the market only once.

### Current Behavior

When posting on market a player is able to post the same kitsu Multiple times for both the different and the same price
The kitsu stays in the 'owned' section so can be listed and re listed.
And stays in 'my nft' section of dex so can still be bred while on the market.

Purchasing the kitsu removes all listing of that kitsu 

Canceling one of the posted removes all the posted ones of that kitsu

### Possible Solution
Alternatively when putting  kitsu up for auction it removes all other listing of that Kitsu from the market. Removes them from the 'owned' section from the my nft section and from the 'my nft' section of dex
Ideally listing at buy now market should act the same as when putting it up for auction.

### Steps to Reproduce

1. Post a kitsu as buy now on market
2. After it's posted go to owned kitsu 
3. Re-select the same kitsu and post it for buy now
4.

### Detailed Description

![Screenshot_20220529-080615_MetaMask](https://user-images.githubusercontent.com/105953165/170880127-0c1d7600-fd89-4106-b9bb-f7888747653d.jpg)
![Screenshot_20220529-082428_MetaMask](https://user-images.githubusercontent.com/105953165/170880128-2dbb3daa-f166-41c7-b729-918a9747feba.jpg)
![Screenshot_20220529-083758_MetaMask](https://user-images.githubusercontent.com/105953165/170880130-46aeefa6-7b11-4239-858a-7e7befdc4459.jpg)
![Screenshot_20220529-083701_MetaMask](https://user-images.githubusercontent.com/105953165/170880133-c5b98b7d-96b3-4f13-83bc-bc017c24df4a.jpg)
![Screenshot_20220529-110638_MetaMask](https://user-images.githubusercontent.com/105953165/170880135-fb66ca98-6a9f-47bc-8a7a-be3877dedd81.jpg)

**Comment by JayArrowz** [comment]
Cannot reproduce? Maybe just a UI issue?

**Comment by Mistbind** [comment]
Possibly? I'll leave the six I posted on market and see what happens, when
I first discovered it, it was because someone else had done it by accident
and I saw there was two of the same one on market.

**Comment by JayArrowz** [comment]
Can confirm this has been fixed - will close
