### ISSUE TITLE
UI didnt show more than 57 NFTs

### ISSUE THREAD

**Issue by Ky0ushu** [Kitsumon/breeding-testnet#48]
I just noticed that my UI didn't not show all of my Kitsus. 

Apparently it does not show more than 57 NFTs and kicks out the oldest when you add a new one

At least there was no "load more" button anymore.

After I refreshed the page the "load more" button re-appeared.

Then after I hatched a hybrid egg it was gone again and I could not load all of my NFTs

I don't know if thats a bug or it was due to loading times, but I thought I report it

**Comment by JayArrowz** [comment]
The UI does not update automatically, when you receive a NFT. Therefore a refresh is required for it to calculate the maximum pages. Added as enhancement. Maybe we want to add a refresh button?

**Comment by JayArrowz** [comment]
Added refresh
