### ISSUE TITLE
Double element

### ISSUE THREAD

**Issue by Mistbind** [Kitsumon/breeding-testnet#49]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ ] Have you cleared your cache? Yes 
- [ ] Enter Browser name and version: .metamask 
- [ ] Enter Wallet name and version: 5.1.1 metamask
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### Expected Behavior

For it not to be possible for a kitsu to have the same element twixe

### Current Behavior

Some kitsu can currently bred to have the same element twice

### Steps to Reproduce

It seems to be connected with the position of the elemental 
If one parent has an element in position 1 while the other parent has the same element in position 2
It's not easy to reproduce but breeding parents with the specifications previously mentioned have a chance of doing it.

### Detailed Description

https://testnets.opensea.io/assets/mumbai/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/828/ 

https://testnets.opensea.io/assets/mumbai/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/247/
![Screenshot_20220601-142322_MetaMask](https://user-images.githubusercontent.com/105953165/171490569-055d6ac2-e634-49d3-b1ad-cfddf553e9dc.jpg)
![Screenshot_20220601-064332_MetaMask](https://user-images.githubusercontent.com/105953165/171490579-4e5686fe-25af-480b-992f-16ddaaf1fbfb.jpg)
![Screenshot_20220601-064329_MetaMask](https://user-images.githubusercontent.com/105953165/171490618-db734e1c-cd2b-43fb-8643-75ac39ffb76b.jpg)

**Comment by JayArrowz** [comment]
![image](https://user-images.githubusercontent.com/49910176/171747974-87fa97b9-26a0-481e-843f-3a8d285deba1.png)
explaination will close

**Comment by Mistbind** [comment]
Cool now we know it wasn't a bug thank you
