### ISSUE TITLE
Cloverfield hybrid front legs missing

### ISSUE THREAD

**Issue by Mistbind** [Kitsumon/breeding-testnet#50]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [ ] Have you cleared your cache? Yes 
- [ ] Enter Browser name and version: .e.g. Chrome 11
- [ ] Enter Wallet name and version: XXX Version x.xx (.e.g Metamask Version 1.2.0)
- [ ] Enter transaction ID if any: XXX

https://testnets.opensea.io/assets/mumbai/0xdb734bcedf06143c85bde40e670ba80d6ad01e19/834/

I think the location of front legs got confused with the back legs because they have the same name.

![Screenshot_20220601-173538_MetaMask](https://user-images.githubusercontent.com/105953165/171514036-e21acdcb-1e36-446a-8ee9-cf7145e4f834.jpg)
![Screenshot_20220601-173528_MetaMask](https://user-images.githubusercontent.com/105953165/171514043-2f49541c-d93c-4816-bc63-624c3915d2ab.jpg)

![Screenshot_20220601-173940_MetaMask](https://user-images.githubusercontent.com/105953165/171514022-822e040b-90b6-42c1-9e78-2ac1da4e2f86.jpg)

![Screenshot_20220601-174252_MetaMask](https://user-images.githubusercontent.com/105953165/171513987-c8e53165-bf97-4014-b894-73d8fdd8cba8.jpg)
![Screenshot_20220601-174008_MetaMask](https://user-images.githubusercontent.com/105953165/171514005-409bb78d-91d0-4090-a5bc-addb40f1f185.jpg)

**Comment by JayArrowz** [comment]
Fixed :)
