### ISSUE TITLE
Who's that kitsumon??

### ISSUE THREAD

**Issue by Xkyee30** [Kitsumon/breeding-testnet#53]
### Expected Behavior
After finishing the loading of the model this happen.

### Current Behavior
Metamask browser mobile

![Screenshot_20220603-104348](https://user-images.githubusercontent.com/106165471/171776684-63a95634-ac90-44ac-ae68-9b00294d2dc6.jpg)

### Steps to Reproduce

1.
2.
3.
4.

**Comment by JayArrowz** [comment]
Fixed
