### ISSUE TITLE
Pheonixa leg color gaps

### ISSUE THREAD

**Issue by Xkyee30** [Kitsumon/breeding-testnet#57]
Lines of pheonixa layering the color.

![Screenshot_20220607-114610](https://user-images.githubusercontent.com/106165471/172291811-50c9e76c-ef77-4f11-82d8-7ed787ebef8f.jpg)
![Screenshot_20220607-114303](https://user-images.githubusercontent.com/106165471/172291832-d1a976f9-b634-478e-89c5-799397f20003.jpg)
![Screenshot_20220607-114217](https://user-images.githubusercontent.com/106165471/172291843-5cad2c39-825e-4b92-88b7-cf05c110eea5.jpg)

**Comment by JayArrowz** [comment]
This is intended ;)
