### ISSUE TITLE
Miscolored back legs 

### ISSUE THREAD

**Issue by Mistbind** [Kitsumon/breeding-testnet#58]
Browser used metamask
Cache was cleared

Issue with breeding nuetronic with a hybrid 
The legs are from negativo and they kept their original colors while rest of body was nuetronic colors.

Token ID 933
Name 
First Confused Surfer

![Screenshot_20220615-062334_MetaMask](https://user-images.githubusercontent.com/105953165/173824658-d7974a8e-11bc-4980-99b6-e5f38520ca5f.jpg)

**Comment by JayArrowz** [comment]
Fixed on update:
![image](https://user-images.githubusercontent.com/49910176/174862838-9b49483f-24c6-4da8-86cd-c893d0624be8.png)
