### ISSUE TITLE
My NFTs button has line break 

### ISSUE THREAD

**Issue by nshCore** [Kitsumon/breeding-testnet#8]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [x] Have you cleared your cache?
- [x] Enter Browser name and version: .e.g. Chrome 11
Chrome Version 101.0.4951.64 
- [x] Enter Wallet name and version: XXX Version x.xx (.e.g Metamask Version 1.2.0)
MetaMask Version 10.14.6
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### Expected Behavior

My NFT's to be on a single line

### Current Behavior

My NFT's has line break between My and NFT's
    
<img width="1431" alt="Screenshot 2022-05-24 at 18 24 11" src="https://user-images.githubusercontent.com/21375475/170147957-25da7e9b-634f-4fae-8d30-8764deb90ed3.png">

### Possible Solution

increase width of button

**Comment by JayArrowz** [comment]
Fixed
