### ISSUE TITLE
Kitsu name on breeding screen doesnt match Figma design

### ISSUE THREAD

**Issue by nshCore** [Kitsumon/breeding-testnet#9]
Figma design shows right hand side Kitsu with name and element tags to the right of the diagonal split

<img width="861" alt="Screenshot 2022-05-24 at 18 52 34" src="https://user-images.githubusercontent.com/21375475/170150301-07b17dc6-3a8f-45c1-b8cc-1a2e85a77681.png">

Implementation shows name and tags covering the diagonal split
<img width="1366" alt="Screenshot 2022-05-24 at 18 53 49" src="https://user-images.githubusercontent.com/21375475/170150422-1bba9f0b-9474-4456-b6ec-866f17aa4f56.png">

¿Add more padding left?

**Comment by JayArrowz** [comment]
This looks like a resize issue theres no issues like this if you refresh the page and the size loads intiailly correctly

**Comment by JayArrowz** [comment]
Fixed
